defaultNamespace: suse-ai
helm:
  chart: oci://dp.apps.rancher.io/charts/milvus
  version: 4.2.2
  releaseName: milvus
  valuesFiles:
    - values.yaml
  credentials:
    - name: application-collection