global:
  imagePullSecrets:
  - application-collection
cluster:
  enabled: false
standalone:
  persistence:
    persistentVolumeClaim:
      storageClass: local-path
etcd:
  replicaCount: 1
  persistence:
    storageClassName: local-path
minio:
  enabled: true
  mode: standalone  # or "distributed" if you want multiple replicas
  replicas: 1
  rootUser: "admin"
  rootPassword: "adminminio"
  persistence:
    enabled: true
    storageClass: local-path
  resources:
    requests:
      memory: 1024Mi
  tls:
    enabled: false  # Make sure this is present to avoid nil pointer issues
kafka:
  enabled: false
  name: kafka
  replicaCount: 3
  broker:
    enabled: true
  cluster:
    listeners:
      client:
        protocol: 'PLAINTEXT'
      controller:
        protocol: 'PLAINTEXT'
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: "local-path" 