defaultNamespace: cattle-neuvector-system
helm:
  # Install the main NeuVector chart
  repo: https://charts.rancher.io
  chart: neuvector
  version: 105.0.2+up2.8.5
  releaseName: neuvector
  valuesFiles:
    - values.yaml
    - values-override.yaml  # This will override values in the previous file 